### ISSUE TITLE
Undefined method 'at' 

### ISSUE THREAD

**Issue by henadzit** [philostler/rspec-sidekiq#106]
Hello,

Thanks for awesome gem! I run into an issue with the matcher `#at`.

``` ruby
SomeJob.perform_at 5.minutes.from_now
expect(SomeJob).to have_enqueued_job().at(5.minutes.from_now)
```

fails with 

```
undefined method 'at' for #<RSpec::Sidekiq::Matchers::HaveEnqueuedJob:0x007fe063d4aa58>
```

Thanks,
Henadzi

**Comment by wpolicarpo** [comment]
@henadzit which version of `rspec-sidekiq` are ou using?

**Comment by henadzit** [comment]
@wpolicarpo sorry, it's `2.2.0`.

**Comment by wpolicarpo** [comment]
@henadzit `#at` and `#in` chainable methods are available only on develop branch. I'll take a look at https://github.com/philostler/rspec-sidekiq/issues/107 before release a new version with those methods.
