### ISSUE TITLE
Wait for the end of transactions before adding jobs to the queue

### ISSUE THREAD

**Issue by Dorian** [philostler/rspec-sidekiq#114]
If a transaction changes the model, the sidekiq job could be fired and executed before the transaction ends, thus getting on old state of the model while the transaction is not finished.

```ruby
class Show < ActiveRecord::Base
  after_commit(on: :update) do
    p previous_changes
  end

  def calculations
    sleep 10
  end
end

show = Show.create!(name: 'The Show', description: 'The Description', artist: 'The Artist')

Show.transaction do
  show.update!(name: 'Another Show')
  show.delay.send_ticket_confirmation
  show.calculations
end
````

Full template for the example: https://gist.github.com/Dorian/3cca25378419922a4405bf9d945b8512

A very simple reduction would be:

```ruby
class Show < ActiveRecord::Base
end

fork do
  show = Show.create!(name: 'The Show')

  Show.transaction do
    puts "---> transaction start"
    show.update!(name: 'Another Show')
    sleep 3
    puts "---> transaction end"
  end
end

fork do
  10.times { |i| p i, Show.last; sleep 1 }
end
```

Which is gonna print something including:

```ruby
---> transaction start
#<Show id: 1, name: "The Show">
---> transaction end
#<Show id: 1, name: "Another Show">
```

Full example: https://gist.github.com/f4740c979b0a5cad3552116570c9ca83

What do you think? I have a 5 seconds delay for now because sending any job to sidekiq because of that.

**Comment by packrat386** [comment]
I think you're looking for the main [Sidekiq](https://github.com/mperham/sidekiq) repo. This is a library for testing those changes, but we don't really determine how stuff gets enqueued.

**Comment by Dorian** [comment]
@packrat386 Oops, thanks, I posted it there: https://github.com/mperham/sidekiq/issues/3330
