### ISSUE TITLE
Release to Rubygems

### ISSUE THREAD

**Issue by anothermh** [philostler/rspec-sidekiq#115]
Are there plans to release to rubygems? The current `lib/rspec/sidekiq/version.rb` shows v3.0.0 but the file was last updated December 2015. The latest version on rubygems is 2.2.0. A new release would be great!

**Comment by PikachuEXE** [comment]
I realize that too
Right now I am using my own workaround + 2.2.0 instead of `master` of this repo
Any release blocker?

**Comment by baburdick** [comment]
👍  I'm using a workaround, too: philostler/rspec-sidekiq#108

**Comment by packrat386** [comment]
Version 3.0.0 is out on rubygems now. https://rubygems.org/gems/rspec-sidekiq/versions/3.0.0

**Comment by baburdick** [comment]
👍  Thanks @packrat386!
