### ISSUE TITLE
have_enqueued_sidekiq_job  "at" function is undefined

### ISSUE THREAD

**Issue by magedmakled** [philostler/rspec-sidekiq#149]
My worker `perform` method doesn't take any argument so I'm trying to test it with 
`expect(MyWorker).to have_enqueued_sidekiq_job().at(Time.now)`
but I'm getting 
` undefined method `at' for #<RSpec::Matchers::BuiltIn::Has:0x007fdce6c35e40>`

Any suggestions?

**Comment by packrat386** [comment]
Can I get a full code sample as well as a version of the library? It looks like it's using some matcher out of the built in ones of RSpec.

**Comment by magedmakled** [comment]
I agree with you on the matcher issue. It also gives me `undefined method configure for RSpec::Sidekiq:Module` 
when I try to 
`RSpec::Sidekiq.configure do |config|` in the `spec_helper` here is my rspec gems
```
rspec (3.6.0)
rspec-core (3.6.0)
rspec-expectations (3.6.0)
rspec-mocks (3.6.0)
rspec-sidekiq (3.0.3)
rspec-support (3.6.0)
```

**Comment by magedmakled** [comment]
Fixed it with `require 'rspec-sidekiq'` in `spec_helper.rb`
