### ISSUE TITLE
Does this gem need a new owner?

### ISSUE THREAD

**Issue by adsteel** [philostler/rspec-sidekiq#186]
I'm not seeing any activity on this gem in the past 2 years, but there are a number of apparently valid, open issues and PRs. I work at Stitch Fix and we use this gem heavily. Personally I love it, it makes my life easier and I'd love to see it continue to grow. I'd be interested in taking over ownership/maintenance if that's an option.

**Comment by bmulholland** [comment]
Given there's no response, I'd say just fork it and start pulling in PRs :)

**Comment by hirowatari** [comment]
Please let us know if you decide to do something with this.  It would be wonderful to have Stich Fix maintain this.

**Comment by philostler** [comment]
Hi! Yeah I don't spend any time in the Ruby world anymore and if there are active users of this gem I'd happily hand it over to anyone that wants to take on it's future maintenance and development. @adsteel Would you prefer being added to the contributors or I believe it's possible to transfer ownership of the repo. From memory I'd have to give push access to Ruby gems as well (been a while since I did anything on this space)

**Comment by adsteel** [comment]
@philostler I spoke too soon about taking this on on behalf of Stitch Fix, but I'm still interested on a personal level. I reached out on LinkedIn, since your contact info here looks like it might be outdated.

**Comment by adsteel** [comment]
Hm, thought I left a comment yesterday, but guess I didn't "send."

@philostler Seems like Linkedin isn't working for communication either. I'd love to be made a contributor, or even take ownership if you'd rather. I've taken this week to poke around and I'd love to help keep this gem alive if I could. If I make decent progress on my own I'll consider publishing a new version under a new name, but I'd love to use this repo if possible.

@packrat386. I see you're a contributor (at least) and a rubygems owner, any chance you're able to give me some permissions here?

**Comment by wspurgin** [comment]
Hi 👋 Fellow interested party in ownership and maintenance. I worked with @adsteel at Stitch Fix too. Happy to be a collaborator/maintainer/co-owner. This gem makes life much easier, and I want to see several of the open PRs/issues continue to make it useful for the Sidekiqs out here ❤️

**Comment by packrat386** [comment]
So, I can't transfer ownership of this repository because I don't have admin privileges on it. I can however merge PRs and release new versions to rubygems.

I've been reluctant to take on requests for new features/releases because I no longer use the gem myself. But @adsteel if you're willing to put in the time reviewing and approving PRs you can ping me when you're ready to have one merged. Similarly if you collate features into a new release version I'm happy enough to push it to rubygems on request. Bit of an awkward workaround for now, but could be workable in the short term?

**Comment by adsteel** [comment]
Unfortunately, I've since left Stitch Fix and am not currently working in Ruby. So I'd suggest you take up @wspurgin 's offer.

@wspurgin [here](https://github.com/philostler/rspec-sidekiq/compare/develop...adsteel:rspec-sidekiq:support-ruby-2-7-thru-3-2?expand=1)'s work I did to bring rspec-sidekiq up to date with Ruby 3.2, and get a new build working on GitHub actions. You're welcome to use any, all or none of it.

**Comment by wspurgin** [comment]
Always a pleasure Adam :heart:

**Comment by packrat386** [comment]
@wspurgin I can extend you the same deal then. If you want to take up the mantle just let me know when you want something merged or released?

**Comment by wspurgin** [comment]
@packrat386 That sounds like a reasonable plan for now. Until @philostler transfers ownership (you can also manage owners [via the RubyGems UI](https://guides.rubygems.org/managing-owners-using-ui/) which might be easier)

**Comment by wspurgin** [comment]
@philostler at your earliest convenience could you:

1. Transfer ownership to me (`wspurgin`), I'm happy to have the repo. Or at least give me "Maintainer" privileges if you want to keep the repo so I have full access for moderation/management
2. Make me the owner or grant push access on RubyGems to `rspec-sidekiq` - I'm `wspur` on RubyGems https://rubygems.org/profiles/wspur

Cheers! 🎉

**Comment by packrat386** [comment]
I can add you as an owner on rubygems. I've sent an invite for that.

I can't give you repo access though unfortunately.

**Comment by philostler** [comment]
HI @wspurgin. I couldn't transfer you ownship. GitHub threw me this error when I tried...

> wspurgin already has a repository in the philostler/rspec-sidekiq network

I have however just added you to the Collaborator list.

**Comment by wspurgin** [comment]
Hey @philostler! Thanks so much! That error is from the fact that I had a fork still. Could you try again? I just deleted it.

**Comment by philostler** [comment]
@wspurgin Transfer request done. I don't touch Ruby anymore now so I'm glad this project is moving on to those that have time to move it forward. Good luck!

P.s. Thanks @wspurgin for taking this on, and @packrat386 for your contributions up to now.

**Comment by wspurgin** [comment]
Thank _you_ @philostler! Transfer complete. We wouldn't be here without your fine work to start with 🚀 

+1 to @packrat386 for all the contributions and helping us out here during the transition.


p.p.s., You may quit Ruby, but Ruby doesn't quit you! 😉
