### ISSUE TITLE
Usage of :be_delayed with ActionMailer

### ISSUE THREAD

**Issue by yabawock** [philostler/rspec-sidekiq#53]
Hi!

I can't seem to figure out how the be_delayed matcher from master is supposed to be used with ActionMailer classes. Since ActionMailer does some funky stuff with instance and class methods I can't use the matchers as documented. 

```ruby
expect(MyMailer.method :notification).to be_delayed('Hello')
```
fails with a NameError: undefined method.
 
I can work around that with a fake `Method` object like this:
```ruby
expect(OpenStruct.new(receiver: MyMailer, name: :notification)).to be_delayed('Hello')
```
but that doesn't feel right at all. 

Any hints on how the matcher is supposed to be used in this case are greatly appreciated.

**Comment by philostler** [comment]
Pull request #63 has been merged into develop now and will be released with v2.1, fixing this issue
