### ISSUE TITLE
#be_delayed doesn't work

### ISSUE THREAD

**Issue by atipugin** [philostler/rspec-sidekiq#65]
I can't figure out why #be_delayed matcher doesn't work for me :( Have the following code:

```ruby
class SomeClass
  def call
    Object.delay.is_a?(Object)
  end
end
```

With spec:
```ruby
require 'rails_helper'

describe SomeClass do
  subject { described_class.new }

  it 'does something' do
    subject.call
    expect(Object.method(:is_a?)).to be_delayed
  end
end
```

And running specs gives this:

```shell
10:58:11 - INFO - Running: spec/services/some_class_spec.rb
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this environment. See https://github.com/philostler/rspec-sidekiq/wiki/FAQ-&-Troubleshooting

SomeClass
  does something (FAILED - 1)

Failures:

  1) SomeClass does something
     Failure/Error: expect(Object.method(:is_a?)).to be_delayed
       expected Object.is_a? to be delayed
     # ./spec/services/some_class_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:61:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:60:in `block (2 levels) in <top (required)>'
```

Any suggestions?

**Comment by atipugin** [comment]
Doh, get it. I need to pass same arguments to #be_delayed call.

**Comment by Ranhiru** [comment]
Thanks @atipugin. That was what was going wrong for me too.

However I was expecting `be_delayed` to work in such a way that if I called it without any arguments, it would just check if it was delayed regardless of the parameters. Something similar to

```
expect(TestService).to have_received(:my_method)
expect(TestService).to have_received(:my_method).with(my_argument) 
```

While the first line would test if it's called and second line would check if it was called with the exact arguments.

**Comment by tfwright** [comment]
I just got bit by this as well. Very surprising behavior. At the very least the failure message should report delayed methods with different arguments.
