### ISSUE TITLE
How can I test the scheduled time?

### ISSUE THREAD

**Issue by ewamarciniak** [philostler/rspec-sidekiq#66]
I have found this code on the Sidekiq page, but it has since been removed:

``` Collector.should have_queued_job_at(date_2,1)```

Is this have_queued_job_at method part of the gem? it doesn't seem to be recognised. Is there any way to test the time that the job has been rescheduled to?

**Comment by philostler** [comment]
Your looking at the wrong gem, the part of the docs you are refering to are related to subelsky's helpers over [here](https://github.com/subelsky/subelsky_power_tools/blob/master/lib/subelsky_power_tools/sidekiq_assertions.rb)

**Comment by philostler** [comment]
I don't think we have anything in here for testing the time the job has been rescheduled for. Not worked on this gem for a while so I may just have forgotten
