### ISSUE TITLE
Dependency conflict with rspec 3.2

### ISSUE THREAD

**Issue by thom-nic** [philostler/rspec-sidekiq#67]
When I bump rspec-rails to `~>3.2.1` in my gemfile I get dependency conflicts:

```
Bundler could not find compatible versions for gem "rspec-mocks":
  In Gemfile:
    rspec-rails (~> 3.2.1) ruby depends on
      rspec-mocks (~> 3.2.0) ruby

    rspec-sidekiq (~> 2.0.0) ruby depends on
      rspec (>= 3.0.0, ~> 3.0) ruby depends on
        rspec-mocks (~> 3.1.0) ruby

```

**Comment by philostler** [comment]
Did you resolve this? I can't see the problem with the RSpec dependency in `rspec-sidekiq`

**Comment by thom-nic** [comment]
Let me check I left the dependency @ `~> 3.1.0`

**Comment by thom-nic** [comment]
Did another `bundle update` after changing `rspec-rails` back to `~> 3.2.1` - looks like it's working now.  Maybe one of the rspec projects updated their dependency range to make it compatible.  Thanks for following up!
