### ISSUE TITLE
have_enqueued_job fails if args includes a Hash

### ISSUE THREAD

**Issue by gPrado** [philostler/rspec-sidekiq#74]
In previous versions (2.0.0), if you had a worker that accepted a hash parameter, you could do the following test:

    expect(Sidekiq::Worker).to have_enqueued_job 123, true, 'param1' => 'abc456'

After update to 2.1.0 it fails with: **TypeError: no implicit conversion of String into Integer**
at: **lib/rspec/matchers/have_enqueued_job.rb:56**

**Comment by erikogan** [comment]
I came across this today. I am about to push a final commit to #77, which fixes the problem.

**Comment by erikogan** [comment]
@gPrado (& @philostler) I believe this issue can be closed with the merge of #77. Can you confirm?

**Comment by philostler** [comment]
Confirmed

**Comment by gPrado** [comment]
Fix confirmed, thank you guys!

**Comment by dentarg** [comment]
@philostler any chance we are getting closer to a release that includes this?
