### ISSUE TITLE
Gem specs fail

### ISSUE THREAD

**Issue by why-el** [philostler/rspec-sidekiq#89]
Hey,

When I run the `rspec-sidekiq` specs locally using `bundle exec rspec spec` I get 4 failures: 

```
rspec ./spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb:29 # RSpec::Sidekiq::Matchers::HaveEnqueuedJob expected usage matches on an enqueued ActiveJob
rspec ./spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb:33 # RSpec::Sidekiq::Matchers::HaveEnqueuedJob expected usage matches on an enqueued ActiveJob by global_id
rspec ./spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb:37 # RSpec::Sidekiq::Matchers::HaveEnqueuedJob expected usage matches on ActionMailer Job
rspec ./spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb:45 # RSpec::Sidekiq::Matchers::HaveEnqueuedJob expected usage matches on ActionMailer with a resource Job
```

All dependencies are installed. I tested this against both ruby `2.1.5` and the latest `2.2.4` and also both the `develop` branch and the `master` branch. Anything more than `bundle exec rspec spec` I need to run or be aware of?

**Comment by freemanoid** [comment]
I got the same errors. I traced the errors and the logic which leads to them seems to be reasonable. Can't understand why doesn't it fail on [travis][1].

[1]: https://travis-ci.org/philostler/rspec-sidekiq/jobs/98411990

**Comment by wpolicarpo** [comment]
@why-el @freemanoid are you still having problems with this?

**Comment by packrat386** [comment]
Doesn't reproduce locally and this is pretty old.
