### ISSUE TITLE
Sidekiq::Batch::Status wrong number of arguments

### ISSUE THREAD

**Issue by codemang** [philostler/rspec-sidekiq#92]
I'm getting an ArgumentError exception when my specs try to instantiate an instance of `Sidekiq::Batch::Status`. 

With one argument, I get `ArgumentError Exception: wrong number of arguments (given 0, expected 2)`
With 2+ arguments I get `ArgumentError Exception: Wrong number of arguments. Expected 1, got n#`

I placed a few break points in the file pertaining to batches and I see the call to the NullBatch initializer is called but **not** the call to NullStatus. Has anyone ever seen this type of behavior?

I also notice that the BatchStatus object only takes one argument, a bid, but the NullStatus takes both a bid and a callback. How does this work?

**Comment by ehsan-khaliki** [comment]
@codemang Were you able to find a solution for this?

**Comment by ehsan-khaliki** [comment]
Having same issue

**Comment by codemang** [comment]
@ehsan-khaliki sorry this is from a while ago, at this point I don't remember. Good luck though.

**Comment by ehsan-khaliki** [comment]
@wpolicarpo @packrat386 @philostler bump

**Comment by ehsan-khaliki** [comment]
rspec-sidekiq (2.2.0)
sidekiq (4.2.9)

status = Sidekiq::Batch::Status.new(@batch.bid)

Failure/Error: status = Sidekiq::Batch::Status.new(@batch.bid)
     
     ArgumentError:
       wrong number of arguments (given 0, expected 2)

**Comment by hale** [comment]
Fixed in https://github.com/philostler/rspec-sidekiq/pull/111
